=== EstebanAC45/xmlvalido_grupo3/Entrega/fichero_email.dtd
<!-- email -->
<!ELEMENT email (asunto, remitente, destinatario, mensaje)>
  <!ATTLIST email fecha CDATA #REQUIRED>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT mensaje (titulo, cuerpo, archivos*, firma)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>
<!ELEMENT archivos (EMPTY)>
<!ELEMENT firma (#PCDATA)>

=== EstebanAC45/xmlvalido_grupo3/Entrega/parte4_ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo.css" ?>
<!DOCTYPE email SYSTEM "fichero_email.dtd">

<email fecha="07/09/2022">
  
    <asunto>GUIA 32- TareaBox</asunto>
    <remitente>tareasbox@yahoo.com</remitente>
    <destinatario>estudiante@gmail.com</destinatario>
    <mensaje>
      <titulo>Tarea EX</titulo>
      <cuerpo>Cuerpo del correo</cuerpo>
      <firma>F.: tareasbox@yahoo.com</firma>
    </mensaje>
    
</email>
