<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/css" href="ejercicio-ii-1a-dtd.css" ?>

<!DOCTYPE liga [
		<!ELEMENT liga (equipo+)>
		<!ELEMENT equipo (nombre, pais, categoria?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (M|F) #REQUIRED>
    <!ATTLIST nombre trofeos  CDATA  #IMPLIED>
		<!ELEMENT pais (#PCDATA)>
		<!ELEMENT categoria (#PCDATA)>
		<!ATTLIST pais departamento CDATA #REQUIRED>
		]>
<liga>
 <equipo>
  <nombre sexo="M" trofeos="16">CD AGUILA</nombre>
  <pais departamento="San Miguel">El Salvador</pais>
  <categoria>Primera División</categoria>
 </equipo>
  
  <equipo>
  <nombre sexo="M" trofeos="18">CD FAS</nombre>
  <pais departamento="Santa Ana">El Salvador</pais>
  <categoria>Primera División</categoria>
 </equipo>
</liga>
