<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/css" href="ejercicio-ii-1b-dtd.css" ?>

<!DOCTYPE menu [
		<!ELEMENT menu (platillo+)>
		<!ELEMENT platillo (nombre, acompañante, bebida*)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre precio CDATA #REQUIRED>
    <!ATTLIST nombre disponibles  CDATA  #REQUIRED>
		<!ELEMENT acompañante (#PCDATA)>
		<!ELEMENT bebida (#PCDATA)>
		<!ATTLIST bebida tipo CDATA #REQUIRED>
		<!ATTLIST menu dia (lunes|martes|miercoles|jueves|viernes) #REQUIRED>
		]>
<menu dia="martes">
 <platillo>
  <nombre precio="$3.50" disponibles="13">Carne asada</nombre>
  <acompañante >Arroz y Ensalada</acompañante>
  <bebida tipo="Fría">Coca Cola</bebida>
  <bebida tipo="Fría">Pilsener</bebida>
 </platillo>

</menu>
